// <auto-generated />
using System;
using DriveTrack.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DriveTrack.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260907184134_DomainModel")]
    partial class DomainModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DriveTrack.Domain.Chat.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    b.Property<int?>("SenderUserId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_user_id");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("SenderUserId")
                        .HasDatabaseName("ix_messages_sender_user_id");

                    b.HasIndex("DriverId", "SentAt")
                        .HasDatabaseName("ix_messages_driver_id_sent_at");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("DriveTrack.Domain.Clients.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_number");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_clients_user_id");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("DriveTrack.Domain.Deliveries.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeliveryNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("delivery_notes");

                    b.Property<int?>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    b.Property<string>("PackageDetails")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("package_details");

                    b.Property<decimal>("PackageWeightKg")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("package_weight_kg");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("WindowEarliestAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_earliest_at");

                    b.Property<DateTimeOffset?>("WindowLatestAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_latest_at");

                    b.HasKey("Id")
                        .HasName("pk_deliveries");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_deliveries_client_id");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_deliveries_driver_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_deliveries_status");

                    b.ToTable("deliveries", null, t =>
                        {
                            t.HasCheckConstraint("CK_Deliveries_DeliveryWindow", "window_earliest_at IS NULL OR window_latest_at IS NULL OR window_earliest_at < window_latest_at")
                                .HasName("ck_deliveries_delivery_window");

                            t.HasCheckConstraint("CK_Deliveries_PackageWeightKg", "package_weight_kg > 0")
                                .HasName("ck_deliveries_package_weight_kg");
                        });
                });

            modelBuilder.Entity("DriveTrack.Domain.Deliveries.NotificationAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_id");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("recipient");

                    b.HasKey("Id")
                        .HasName("pk_notification_attempts");

                    b.HasIndex("DeliveryId")
                        .HasDatabaseName("ix_notification_attempts_delivery_id");

                    b.ToTable("notification_attempts", (string)null);
                });

            modelBuilder.Entity("DriveTrack.Domain.Deliveries.ProofAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<int>("ProofOfDeliveryId")
                        .HasColumnType("integer")
                        .HasColumnName("proof_of_delivery_id");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_key");

                    b.HasKey("Id")
                        .HasName("pk_proof_assets");

                    b.HasIndex("ProofOfDeliveryId")
                        .HasDatabaseName("ix_proof_assets_proof_of_delivery_id");

                    b.ToTable("proof_assets", (string)null);
                });

            modelBuilder.Entity("DriveTrack.Domain.Deliveries.ProofOfDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<int?>("CapturedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("captured_by_user_id");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_id");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("recipient_name");

                    b.HasKey("Id")
                        .HasName("pk_proof_of_deliveries");

                    b.HasIndex("CapturedByUserId")
                        .HasDatabaseName("ix_proof_of_deliveries_captured_by_user_id");

                    b.HasIndex("DeliveryId")
                        .IsUnique()
                        .HasDatabaseName("ix_proof_of_deliveries_delivery_id");

                    b.ToTable("proof_of_deliveries", (string)null);
                });

            modelBuilder.Entity("DriveTrack.Domain.Deliveries.TimelineEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_display_name");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actor_role");

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("integer")
                        .HasColumnName("actor_user_id");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_id");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("new_status");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("previous_status");

                    b.HasKey("Id")
                        .HasName("pk_timeline_entries");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_timeline_entries_actor_user_id");

                    b.HasIndex("DeliveryId", "OccurredAt")
                        .HasDatabaseName("ix_timeline_entries_delivery_id_occurred_at");

                    b.ToTable("timeline_entries", (string)null);
                });

            modelBuilder.Entity("DriveTrack.Domain.Drivers.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("license_number");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_drivers");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_drivers_user_id");

                    b.HasIndex("VehicleId")
                        .IsUnique()
                        .HasDatabaseName("ix_drivers_vehicle_id")
                        .HasFilter("vehicle_id IS NOT NULL");

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("DriveTrack.Domain.Reviews.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_id");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_reviews_client_id");

                    b.HasIndex("DeliveryId")
                        .IsUnique()
                        .HasDatabaseName("ix_reviews_delivery_id");

                    b.ToTable("reviews", null, t =>
                        {
                            t.HasCheckConstraint("CK_Reviews_Rating", "rating >= 1 AND rating <= 5")
                                .HasName("ck_reviews_rating");
                        });
                });

            modelBuilder.Entity("DriveTrack.Domain.Shifts.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id")
                        .HasName("pk_shifts");

                    b.HasIndex("DriverId")
                        .IsUnique()
                        .HasDatabaseName("ix_shifts_driver_id_open")
                        .HasFilter("ended_at IS NULL");

                    b.ToTable("shifts", (string)null);
                });

            modelBuilder.Entity("DriveTrack.Domain.Vehicles.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CapacityKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("capacity_kg");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("license_plate");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer")
                        .HasColumnName("mileage");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<DateOnly?>("NextMaintenanceDate")
                        .HasColumnType("date")
                        .HasColumnName("next_maintenance_date");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("LicensePlate")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicles_license_plate");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("DriveTrack.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("email_index");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("user_name_index");

                    b.ToTable("asp_net_users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("role_name_index");

                    b.ToTable("asp_net_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("asp_net_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_asp_net_user_roles_user_id");

                    b.ToTable("asp_net_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("DriveTrack.Domain.Chat.Message", b =>
                {
                    b.HasOne("DriveTrack.Domain.Drivers.Driver", null)
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_drivers_driver_id");
                });

            modelBuilder.Entity("DriveTrack.Domain.Deliveries.Delivery", b =>
                {
                    b.HasOne("DriveTrack.Domain.Clients.Client", null)
                        .WithMany("Deliveries")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_deliveries_clients_client_id");

                    b.HasOne("DriveTrack.Domain.Drivers.Driver", null)
                        .WithMany("Deliveries")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_deliveries_drivers_driver_id");

                    b.OwnsOne("DriveTrack.Domain.Common.Location", "DropoffLocation", b1 =>
                        {
                            b1.Property<int>("DeliveryId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("dropoff_address");

                            b1.Property<DateTimeOffset?>("AddressResolvedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("dropoff_address_resolved_at");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("dropoff_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("dropoff_longitude");

                            b1.HasKey("DeliveryId")
                                .HasName("pk_deliveries");

                            b1.ToTable("deliveries");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryId")
                                .HasConstraintName("fk_deliveries_deliveries_id");
                        });

                    b.OwnsOne("DriveTrack.Domain.Common.Location", "PickupLocation", b1 =>
                        {
                            b1.Property<int>("DeliveryId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("pickup_address");

                            b1.Property<DateTimeOffset?>("AddressResolvedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("pickup_address_resolved_at");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("pickup_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("pickup_longitude");

                            b1.HasKey("DeliveryId")
                                .HasName("pk_deliveries");

                            b1.ToTable("deliveries");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryId")
                                .HasConstraintName("fk_deliveries_deliveries_id");
                        });

                    b.Navigation("DropoffLocation")
                        .IsRequired();

                    b.Navigation("PickupLocation")
                        .IsRequired();
                });

            modelBuilder.Entity("DriveTrack.Domain.Deliveries.NotificationAttempt", b =>
                {
                    b.HasOne("DriveTrack.Domain.Deliveries.Delivery", null)
                        .WithMany()
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_attempts_deliveries_delivery_id");
                });

            modelBuilder.Entity("DriveTrack.Domain.Deliveries.ProofAsset", b =>
                {
                    b.HasOne("DriveTrack.Domain.Deliveries.ProofOfDelivery", null)
                        .WithMany("Assets")
                        .HasForeignKey("ProofOfDeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proof_assets_proof_of_deliveries_proof_of_delivery_id");
                });

            modelBuilder.Entity("DriveTrack.Domain.Deliveries.ProofOfDelivery", b =>
                {
                    b.HasOne("DriveTrack.Domain.Deliveries.Delivery", null)
                        .WithOne("ProofOfDelivery")
                        .HasForeignKey("DriveTrack.Domain.Deliveries.ProofOfDelivery", "DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proof_of_deliveries_deliveries_delivery_id");

                    b.OwnsOne("DriveTrack.Domain.Common.Location", "CaptureLocation", b1 =>
                        {
                            b1.Property<int>("ProofOfDeliveryId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("capture_address");

                            b1.Property<DateTimeOffset?>("AddressResolvedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("capture_address_resolved_at");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("capture_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("capture_longitude");

                            b1.HasKey("ProofOfDeliveryId")
                                .HasName("pk_proof_of_deliveries");

                            b1.ToTable("proof_of_deliveries");

                            b1.WithOwner()
                                .HasForeignKey("ProofOfDeliveryId")
                                .HasConstraintName("fk_proof_of_deliveries_proof_of_deliveries_id");
                        });

                    b.Navigation("CaptureLocation")
                        .IsRequired();
                });

            modelBuilder.Entity("DriveTrack.Domain.Deliveries.TimelineEntry", b =>
                {
                    b.HasOne("DriveTrack.Domain.Deliveries.Delivery", null)
                        .WithMany()
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_timeline_entries_deliveries_delivery_id");
                });

            modelBuilder.Entity("DriveTrack.Domain.Drivers.Driver", b =>
                {
                    b.HasOne("DriveTrack.Domain.Vehicles.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_drivers_vehicles_vehicle_id");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("DriveTrack.Domain.Reviews.Review", b =>
                {
                    b.HasOne("DriveTrack.Domain.Clients.Client", null)
                        .WithMany("Reviews")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_clients_client_id");

                    b.HasOne("DriveTrack.Domain.Deliveries.Delivery", null)
                        .WithOne("Review")
                        .HasForeignKey("DriveTrack.Domain.Reviews.Review", "DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_deliveries_delivery_id");
                });

            modelBuilder.Entity("DriveTrack.Domain.Shifts.Shift", b =>
                {
                    b.HasOne("DriveTrack.Domain.Drivers.Driver", null)
                        .WithMany("Shifts")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shifts_drivers_driver_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("DriveTrack.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("DriveTrack.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("DriveTrack.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("DriveTrack.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("DriveTrack.Domain.Clients.Client", b =>
                {
                    b.Navigation("Deliveries");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("DriveTrack.Domain.Deliveries.Delivery", b =>
                {
                    b.Navigation("ProofOfDelivery");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("DriveTrack.Domain.Deliveries.ProofOfDelivery", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("DriveTrack.Domain.Drivers.Driver", b =>
                {
                    b.Navigation("Deliveries");

                    b.Navigation("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
